SELECT 
    'CREATE TABLE [' + t.TABLE_NAME + '] (' +
    STRING_AGG(
        '[' + c.COLUMN_NAME + '] ' + c.DATA_TYPE + 
        CASE WHEN c.CHARACTER_MAXIMUM_LENGTH IS NOT NULL AND c.CHARACTER_MAXIMUM_LENGTH > 0 
             THEN '(' + CAST(c.CHARACTER_MAXIMUM_LENGTH AS VARCHAR) + ')' 
             ELSE '' END +
        CASE WHEN c.IS_NULLABLE = 'NO' THEN ' NOT NULL' ELSE ' NULL' END,
        ', '
    ) + ');'
FROM INFORMATION_SCHEMA.TABLES t
JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_TYPE = 'BASE TABLE'
AND t.TABLE_NAME != '__EFMigrationsHistory'
GROUP BY t.TABLE_NAME